---
- name: homework37
  hosts: all
  become: true
  pre_tasks:
    - name: set Time_zone
      timezone:
        name: Europe/Moscow

- name: config router machine
  hosts: router
  become: true
  roles:
    - config_router

- name: config server machine
  hosts: server
  become: true
  roles:
    - iproute
    - knock-client
    - nginx
    